# Generated by Django 2.2.7 on 2019-11-06 16:38

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GDTemplateTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=36)),
                ('sid', models.CharField(max_length=36)),
                ('nid', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'gd_template_trackers',
                'verbose_name': 'gd_template_tracker',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='KqClone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=36)),
                ('cid', models.CharField(max_length=36)),
                ('result', models.TextField()),
                ('valid', models.IntegerField()),
                ('eval_score', models.IntegerField()),
                ('count', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'kqclones',
                'verbose_name': 'kqclone',
                'ordering': ('-time_stamp',),
            },
        ),
        migrations.CreateModel(
            name='KqJsons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=36)),
                ('sid', models.CharField(max_length=36)),
                ('cid', models.CharField(max_length=36)),
                ('json', jsonfield.fields.JSONField()),
                ('seq_id', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'kqjsons',
                'verbose_name': 'kqjson',
                'ordering': ('-time_stamp',),
            },
        ),
        migrations.CreateModel(
            name='SessionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=36)),
                ('cid', models.CharField(max_length=36)),
                ('notebook_cid', models.CharField(max_length=12)),
                ('cid_hash', models.CharField(max_length=36)),
                ('code_id', models.IntegerField()),
                ('source', models.TextField()),
                ('output', models.TextField()),
                ('code_eval', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'session_details',
                'verbose_name': 'session_detail',
                'ordering': ('-time_stamp',),
            },
        ),
    ]
