# Generated by Django 2.2.7 on 2019-11-13 09:23

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaffoldJsons',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=36)),
                ('json', jsonfield.fields.JSONField()),
            ],
            options={
                'verbose_name': 'scaffoldjson',
                'verbose_name_plural': 'scaffoldjsons',
            },
        ),
    ]
